/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.hiralpatel.cli;

public class AppCli {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new AppCli().getGreeting());
    }
}
